version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=EMR_Password123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EMRDatabase;User Id=sa;Password=EMR_Password123!;TrustServerCertificate=true;
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    restart: unless-stopped

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  sqlserver_data: